// <auto-generated/>
using System.Reflection;

[assembly: AssemblyProductAttribute("EventStore.Reactive")]
[assembly: AssemblyCompanyAttribute("Alexey Zimarev")]
[assembly: AssemblyCopyrightAttribute("Copyright � 2016 Alexey Zimarev")]
[assembly: AssemblyVersionAttribute("0.1.0.0")]
[assembly: AssemblyFileVersionAttribute("0.1.0.0")]
[assembly: AssemblyInformationalVersionAttribute("0.1.0-unstable.13+Branch.develop.Sha.71794ce82c820b0dd065e339cff945270512e7c9")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyProduct = "EventStore.Reactive";
        internal const System.String AssemblyCompany = "Alexey Zimarev";
        internal const System.String AssemblyCopyright = "Copyright � 2016 Alexey Zimarev";
        internal const System.String AssemblyVersion = "0.1.0.0";
        internal const System.String AssemblyFileVersion = "0.1.0.0";
        internal const System.String AssemblyInformationalVersion = "0.1.0-unstable.13+Branch.develop.Sha.71794ce82c820b0dd065e339cff945270512e7c9";
    }
}
